"""
Django settings for zerowaste project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

logs_dir = os.path.join(BASE_DIR, 'Logs')
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)
import os

log_file = os.path.join(logs_dir, 'zerowaste.log')
if os.path.exists(log_file):
    with open(log_file, 'w'):
        pass  # Golește conținutul fișierului


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)dn0eeifdmtbr&*qxkvttqor9f$uk$w1l!)5j#7a_c45tad*17"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.100.92","192.168.100.97",'127.0.0.1', 'localhost', '192.168.1.9', '192.168.101.17', '192.168.100.186'] 


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",
    "product",
    "rest_framework",
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    "corsheaders",
    'channels',
    'celery'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTH_USER_MODEL = 'api.User'  
ASGI_APPLICATION = 'zerowaste.asgi.application'

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }

#! nu stergeti asta, e pentru cand rulez pentru websocket si bonuri, va las cel de sus sa nu va crape la postman
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # Redis trebuie să ruleze pe acest port
        },
    },
}

# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your email provider's SMTP host
EMAIL_PORT = 587  # Use 465 for SSL, or 587 for TLS
EMAIL_USE_TLS = True  # Use TLS if using port 587
EMAIL_USE_SSL = False  # Use SSL if using port 465
EMAIL_HOST_USER = 'zerowastenoreply@gmail.com'  # Replace with your email address
EMAIL_HOST_PASSWORD = 'xvbk bkgf hhqf ufia'  # Replace with your email password

# JWT settings (optional, you can adjust token lifetime)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "zerowaste.urls"
CORS_ALLOWED_ORIGINS = ["http://192.168.100.97:8100", 'http://localhost:8100', 'http://192.168.100.186:8100', 'http://192.168.101.17:8100'] 

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "zerowaste.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES={
#     "default":{
#       "ENGINE": "django.db.backends.postgresql_psycopg2",
#       "NAME": "zerowaste",
#       "USER": "postgres",
#       "PASSWORD": "postgres",
#       "HOST": "localhost",
#       "PORT": "5432",
#   }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Bucharest"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_BROKER_URL = 'redis://localhost:6379/1'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'

CELERY_TIMEZONE = 'Europe/Bucharest'
CELERY_ENABLE_UTC = True

TESTING = 'test' in sys.argv

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2", 
    }
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{message}',
            'style': '{',
        },
    },
    'filters': {
        # Filtru care exclude nivelul INFO
        'exclude_info': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: record.levelname != 'INFO',
        },
    },
    'handlers': {
        # Handler pentru scrierea în consolă (include toate nivelurile)
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Handler pentru scrierea în fișier (exclude INFO)
        'zerowaste_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join('Logs', 'zerowaste.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Logger pentru evenimentele Daphne (inclusiv WebSocket)
        'daphne': {
            'handlers': ['console', 'zerowaste_file'],  # Trimite logurile atât în consolă, cât și în fișier
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

